plugins {
	id 'java-library'
	id 'eclipse'
	id 'idea'
	id 'maven-publish'
	id 'net.neoforged.gradle.userdev' version '7.0.170'
	id 'net.neoforged.gradle.mixin' version '7.0.170'
}

tasks.named('wrapper', Wrapper).configure {
	// Define wrapper values here so as to not have to always do so when updating gradlew.properties.
	// Switching this to Wrapper.DistributionType.ALL will download the full gradle sources that comes with
	// documentation attached on cursor hover of gradle classes and methods. However, this comes with increased
	// file size for Gradle. If you do switch this to ALL, run the Gradle wrapper task twice afterwards.
	// (Verify by checking gradle/wrapper/gradle-wrapper.properties to see if distributionUrl now points to `-all`)
	distributionType = Wrapper.DistributionType.BIN
}

version = project.mod_version
group = project.maven_group

base {
	archivesName = project.archives_base_name
}

//minecraft.accessTransformers.file rootProject.file('src/main/resources/META-INF/accesstransformer.cfg')

//mixin {
//	config "terrastorage.client.mixins.json"
//}

// runs arguments
runs {
	client {
		workingDirectory project.file('runs/client')
//        jvmArgs "-Dmixin.debug.export=true"
		systemProperty 'mixin.env.remapRefMap', 'true'
		systemProperty 'mixin.env.refMapRemappingFile', "${buildDir}/createSrgToMcp/output.srg"
		programArguments.addAll '--username', 'Dev', '--width', '400', '--height', '200'
		dependencies {
//            runtime("curse.maven:jei-238222:5846880")
//            runtime("mezz.jei:jei-1.21.1-neoforge:19.21.0.247")
		}
	}

	server {
		workingDirectory project.file('runs/server')
		programArgument '--nogui'
		systemProperty 'mixin.env.disableRefMap', 'true'
		systemProperty 'mixin.env.remapRefMap', 'true'
		systemProperty 'mixin.env.refMapRemappingFile', "${projectDir}/build/createSrgToMcp/output.srg"
	}

	data {
		workingDirectory project.file('runs/data')
		systemProperty 'mixin.env.disableRefMap', 'true'
		programArguments.addAll '--mod', 'alloy-forgery', '--all', '--output', file('src/generated/resources/').getAbsolutePath()
	}
}

repositories {
	mavenCentral()
	maven { url "https://maven.terraformersmc.com/releases/" }
	maven { url 'https://maven.wispforest.io' }
	maven { url "https://maven.shedaniel.me/" }
	maven { url "https://maven.su5ed.dev/releases" } // forgified fabric api
	maven {
		name "ipnRepositoryReleases"
		url "https://maven.ipn-mod.org/releases"
	}
	maven {
		url "https://cursemaven.com"
		content {
			includeGroup "curse.maven"
		}
	}
	exclusiveContent {
		forRepository {
			maven {
				name = "Modrinth"
				url = "https://api.modrinth.com/maven"
			}
		}
		filter {
			includeGroup "maven.modrinth"
		}
	}
	flatDir {
		dir 'libs'
	}
}

configurations {
	nightConfigExtract
}

dependencies {
	implementation "net.neoforged:neoforge:${neo_version}"

//	// Fabric API.
//	modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
	compileOnly "org.sinytra.forgified-fabric-api:forgified-fabric-api:${project.fabric_version}"

	// NightConfig.
	nightConfigExtract compileOnly("com.electronwill.night-config:core:${project.night_config_version}")
	nightConfigExtract compileOnly("com.electronwill.night-config:toml:${project.night_config_version}")

	// ModMenu integration.
	compileOnly "com.terraformersmc:modmenu:${project.mod_menu_version}"

	// Expanded Storage compatibility.
	compileOnly "curse.maven:expanded-storage-978068:${project.expanded_storage_version}"
    // Inventory Profiles Next compatibility.
	compileOnly "org.anti_ad.mc:libIPN-neoforge-1.21:6.0.0:dev"
	compileOnly "org.anti_ad.mc:InventoryProfilesNext-neoforge-1.21:2.0.3"
	// sopthisticated storage compatibility
//	implementation "curse.maven:sophisticated-core-618298:6317050"
//	implementation "curse.maven:sophisticated-storage-619320:6303389"
//	implementation "curse.maven:sophisticated-backpacks-422301:6303380"
	implementation "curse.maven:sophisticated-core-618298:6214886"
	implementation "curse.maven:sophisticated-storage-619320:6194158"
	implementation "curse.maven:sophisticated-backpacks-422301:6194170"
	implementation "curse.maven:sophisticated-storage-in-motion-1166930:6270431"
	// nether chest compatibility
//	implementation "curse.maven:puzzles-lib-495476:6311123"
	implementation "curse.maven:puzzles-lib-495476:6283540"
	implementation "curse.maven:new-nether-chest-857971:5733766"
	compileOnly "libs:limitlesscontainers:neoforge-21.1.0"
	// chest with legs compatibility
//	implementation "curse.maven:geckolib-388172:6304958"
	implementation "curse.maven:geckolib-388172:6027599"
	implementation "maven.modrinth:chest-with-legs:jm6Tf76l"
	// snowy spirit compatibility
//	implementation "curse.maven:selene-499980:6324921"
	implementation "curse.maven:selene-499980:6106442"
	implementation "curse.maven:snowy-spirit-566142:5983882"
}

tasks.register("extractNightConfig", Copy) {
	from {
		configurations.nightConfigExtract.collect { zipTree(it) }
	}
	into layout.buildDirectory.dir("nightconfig")
	duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

// Include resources generated by data generators.
sourceSets.main.resources { srcDir 'src/generated' }

processResources {
	inputs.property "version", project.version
	filteringCharset "UTF-8"

	filesMatching("META-INF/neoforge.mods.toml") {
		expand "version": project.version
	}
}

// Mojang ships Java 21 to end users starting in 1.20.5, so mods should target Java 21.
java.toolchain.languageVersion = JavaLanguageVersion.of(21)

java {
	// Loom will automatically attach sourcesJar to a RemapSourcesJar task and to the "build" task
	// if it is present.
	// If you remove this line, sources will not be generated.
	withSourcesJar()

	sourceCompatibility = JavaVersion.VERSION_21
	targetCompatibility = JavaVersion.VERSION_21
}

jar {
//	dependsOn("extractNightConfig")
//
//	from(layout.buildDirectory.dir("nightconfig")) {
//		into ""
//	}

	from("LICENSE") {
		rename { "${it}_${project.base.archivesName.get()}"}
	}
}

//tasks.named("remapJar") {
//	destinationDirectory = layout.buildDirectory.dir("libs/${project.minecraft_version_range}")
//	archiveFileName = "${project.archives_base_name}-${project.mod_version}+${project.minecraft_version_range}.jar"
//}
//
//tasks.named("remapSourcesJar") {
//	destinationDirectory = layout.buildDirectory.dir("libs/${project.minecraft_version_range}")
//	archiveFileName = "${project.archives_base_name}-${project.mod_version}+${project.minecraft_version_range}-sources.jar"
//}
