modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT"

[[mixins]]
config="terrastorage.mixins.json"

#[[accessTransformers]]
#file="META-INF/accesstransformer.cfg"

[[mods]]
modId = "terrastorage"
version = "${version}"
displayName = "Terrastorage"
logoFile = "assets/terrastorage/icon.png"
updateJSONURL = ""
displayURL = "https://modrinth.com/mod/terrastorage"
authors = "TimVinci"
description = '''
Brings Terraria's amazing storage features to Minecraft!
'''

[[dependencies.terrastorage]]
modId = "neoforge"
type="required"
versionRange = "[21.1.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.terrastorage]]
modId = "minecraft"
type="required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.terrastorage]]
modId = "fabric_api"
type="required"
versionRange = "*"
ordering = "NONE"
side = "BOTH"

[[dependencies.terrastorage]]
modId = "inventoryprofilesnext"
type="optional"
versionRange = "*"
ordering = "NONE"
side = "BOTH"
